[package]
name = "r8"
version = "12.8.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "r8"
path = "src/bin/r8.rs"

[[bin]]
name = "rd8"
path = "src/bin/rd8.rs"


[[bin]]
name = "r8x"
path = "src/bin/r8x.rs"

[[bin]]
name = "d8"
path = "src/bin/d8.rs"

[dependencies]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
