//! Full AArch64 (ARM64) Machine Code Assembler (`MacroAssembler`).
//!
//! Encodes 32-bit fixed-width ARM64 binary instructions for 64-bit arithmetic,
//! memory loads/stores, branch backpatching, and AAPCS64 calling conventions.

use crate::compiler::backend::label::{Label, LabelManager};
use crate::compiler::backend::registers::Arm64Register;
use crate::compiler::backend::Condition;

/// Emits raw AArch64 machine code instructions (32-bit words, little-endian).
#[derive(Clone, Debug, Default)]
pub struct Arm64Assembler {
    code: Vec<u8>,
    label_manager: LabelManager,
}

impl Arm64Assembler {
    pub fn new() -> Self {
        Self {
            code: Vec::with_capacity(256),
            label_manager: LabelManager::new(),
        }
    }

    /// Returns current instruction stream offset in bytes.
    #[inline]
    pub fn offset(&self) -> usize {
        self.code.len()
    }

    /// Consumes the assembler and returns the generated byte array.
    pub fn finalize(self) -> Vec<u8> {
        self.code
    }

    /// Emits a 32-bit little-endian ARM64 instruction word.
    #[inline]
    pub fn emit_insn(&mut self, insn: u32) {
        self.code.extend_from_slice(&insn.to_le_bytes());
    }

    /// Creates a new unbound label.
    pub fn create_label(&mut self) -> Label {
        self.label_manager.create_label()
    }

    /// Binds a label and patches pending branch instruction displacements.
    pub fn bind(&mut self, label: Label) {
        let current = self.offset();
        let pending = self.label_manager.bind(label, current);
        for patch_pos in pending {
            let mut insn = u32::from_le_bytes(
                self.code[patch_pos..patch_pos + 4].try_into().unwrap(),
            );
            let branch_pc = patch_pos;
            let offset_bytes = current as isize - branch_pc as isize;
            let offset_insns = (offset_bytes / 4) as i32;

            if (insn & 0xFC000000) == 0x14000000 {
                // B imm26
                insn = (insn & 0xFC000000) | ((offset_insns as u32) & 0x03FFFFFF);
            } else if (insn & 0xFF000010) == 0x54000000 {
                // B.cond imm19
                insn = (insn & 0xFF00001F) | (((offset_insns as u32) & 0x0007FFFF) << 5);
            }
            self.code[patch_pos..patch_pos + 4].copy_from_slice(&insn.to_le_bytes());
        }
    }

    // -------------------------------------------------------------------------
    // Function Prologue and Epilogue (AAPCS64)
    // -------------------------------------------------------------------------

    /// Emits standard ARM64 function prologue:
    /// `stp x29, x30, [sp, -16]!; mov x29, sp; sub sp, sp, #stack_size`
    pub fn emit_prologue(&mut self, stack_size: u32) {
        // stp x29, x30, [sp, -16]! (pre-index)
        self.emit_insn(0xA9BF7BFD);
        // mov x29, sp -> add x29, sp, #0
        self.add_imm(Arm64Register::X29, Arm64Register::Sp, 0);
        // sub sp, sp, #aligned_size
        let aligned = (stack_size + 15) & !15;
        if aligned > 0 {
            self.sub_imm(Arm64Register::Sp, Arm64Register::Sp, aligned);
        }
    }

    /// Emits standard ARM64 function epilogue:
    /// `mov sp, x29; ldp x29, x30, [sp], 16; ret`
    pub fn emit_epilogue(&mut self) {
        // mov sp, x29 -> add sp, x29, #0
        self.add_imm(Arm64Register::Sp, Arm64Register::X29, 0);
        // ldp x29, x30, [sp], 16 (post-index)
        self.emit_insn(0xA8C17BFD);
        // ret
        self.ret();
    }

    // -------------------------------------------------------------------------
    // Move Instructions
    // -------------------------------------------------------------------------

    /// `mov dst, src` -> `orr dst, xzr, src`
    pub fn mov_reg_reg(&mut self, dst: Arm64Register, src: Arm64Register) {
        let insn = 0xAA0003E0 | ((src.code() as u32) << 16) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `movz dst, #imm16, lsl #hw` (load 16-bit immediate chunk)
    pub fn movz(&mut self, dst: Arm64Register, imm16: u16, shift_idx: u8) {
        let hw = (shift_idx & 0x3) as u32;
        let insn = 0xD2800000 | (hw << 21) | ((imm16 as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `movk dst, #imm16, lsl #hw` (keep and replace 16-bit chunk)
    pub fn movk(&mut self, dst: Arm64Register, imm16: u16, shift_idx: u8) {
        let hw = (shift_idx & 0x3) as u32;
        let insn = 0xF2800000 | (hw << 21) | ((imm16 as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// Loads an arbitrary 64-bit constant into register using movz + up to 3 movk instructions.
    pub fn mov_imm64(&mut self, dst: Arm64Register, val: u64) {
        let chunk0 = (val & 0xFFFF) as u16;
        let chunk1 = ((val >> 16) & 0xFFFF) as u16;
        let chunk2 = ((val >> 32) & 0xFFFF) as u16;
        let chunk3 = ((val >> 48) & 0xFFFF) as u16;

        self.movz(dst, chunk0, 0);
        if chunk1 != 0 || chunk2 != 0 || chunk3 != 0 {
            self.movk(dst, chunk1, 1);
        }
        if chunk2 != 0 || chunk3 != 0 {
            self.movk(dst, chunk2, 2);
        }
        if chunk3 != 0 {
            self.movk(dst, chunk3, 3);
        }
    }

    // -------------------------------------------------------------------------
    // Arithmetic & Bitwise
    // -------------------------------------------------------------------------

    /// `add dst, rn, rm` (64-bit register)
    pub fn add(&mut self, dst: Arm64Register, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0x8B000000 | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `add dst, rn, #imm12` (64-bit immediate)
    pub fn add_imm(&mut self, dst: Arm64Register, rn: Arm64Register, imm12: u32) {
        let insn = 0x91000000 | ((imm12 & 0xFFF) << 10) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `sub dst, rn, rm` (64-bit register)
    pub fn sub(&mut self, dst: Arm64Register, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0xCB000000 | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `sub dst, rn, #imm12` (64-bit immediate)
    pub fn sub_imm(&mut self, dst: Arm64Register, rn: Arm64Register, imm12: u32) {
        let insn = 0xD1000000 | ((imm12 & 0xFFF) << 10) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `mul dst, rn, rm`
    pub fn mul(&mut self, dst: Arm64Register, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0x9B007C00 | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `sdiv dst, rn, rm`
    pub fn sdiv(&mut self, dst: Arm64Register, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0x9AC00C00 | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `and dst, rn, rm`
    pub fn and(&mut self, dst: Arm64Register, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0x8A000000 | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `orr dst, rn, rm`
    pub fn orr(&mut self, dst: Arm64Register, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0xAA000000 | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    /// `eor dst, rn, rm`
    pub fn eor(&mut self, dst: Arm64Register, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0xCA000000 | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5) | (dst.code() as u32);
        self.emit_insn(insn);
    }

    // -------------------------------------------------------------------------
    // Memory Load and Store
    // -------------------------------------------------------------------------

    /// `ldr rt, [rn, #offset_bytes]` (64-bit unsigned scaled offset)
    pub fn ldr_offset(&mut self, rt: Arm64Register, rn: Arm64Register, offset_bytes: u32) {
        let scaled = (offset_bytes / 8) & 0xFFF;
        let insn = 0xF9400000 | (scaled << 10) | ((rn.code() as u32) << 5) | (rt.code() as u32);
        self.emit_insn(insn);
    }

    /// `str rt, [rn, #offset_bytes]` (64-bit unsigned scaled offset)
    pub fn str_offset(&mut self, rt: Arm64Register, rn: Arm64Register, offset_bytes: u32) {
        let scaled = (offset_bytes / 8) & 0xFFF;
        let insn = 0xF9000000 | (scaled << 10) | ((rn.code() as u32) << 5) | (rt.code() as u32);
        self.emit_insn(insn);
    }

    // -------------------------------------------------------------------------
    // Comparisons and Control Flow
    // -------------------------------------------------------------------------

    /// `cmp rn, rm` -> `subs xzr, rn, rm`
    pub fn cmp(&mut self, rn: Arm64Register, rm: Arm64Register) {
        let insn = 0xEB00001F | ((rm.code() as u32) << 16) | ((rn.code() as u32) << 5);
        self.emit_insn(insn);
    }

    /// `b label` (unconditional branch)
    pub fn b(&mut self, label: Label) {
        let patch_pos = self.offset();
        self.emit_insn(0x14000000);
        if let Some(target) = self.label_manager.record_use(label, patch_pos) {
            let offset_insns = ((target as isize - patch_pos as isize) / 4) as i32;
            let patched = 0x14000000 | ((offset_insns as u32) & 0x03FFFFFF);
            self.code[patch_pos..patch_pos + 4].copy_from_slice(&patched.to_le_bytes());
        }
    }

    /// `b.cond label` (conditional branch)
    pub fn b_cond(&mut self, cond: Condition, label: Label) {
        let cond_code = Self::arm64_condition(cond);
        let patch_pos = self.offset();
        self.emit_insn(0x54000000 | cond_code);
        if let Some(target) = self.label_manager.record_use(label, patch_pos) {
            let offset_insns = ((target as isize - patch_pos as isize) / 4) as i32;
            let patched = 0x54000000 | (((offset_insns as u32) & 0x0007FFFF) << 5) | cond_code;
            self.code[patch_pos..patch_pos + 4].copy_from_slice(&patched.to_le_bytes());
        }
    }

    /// `ret` (returns to address in x30 / lr)
    pub fn ret(&mut self) {
        self.emit_insn(0xD65F03C0);
    }

    /// Maps abstract `Condition` to AArch64 condition code (0..15).
    pub fn arm64_condition(cond: Condition) -> u32 {
        match cond {
            Condition::Equal => 0x0,              // EQ
            Condition::NotEqual => 0x1,           // NE
            Condition::AboveOrEqual => 0x2,       // CS / HS
            Condition::Below => 0x3,              // CC / LO
            Condition::Overflow => 0x6,           // VS
            Condition::NoOverflow => 0x7,         // VC
            Condition::Above => 0x8,              // HI
            Condition::BelowOrEqual => 0x9,       // LS
            Condition::GreaterThanOrEqual => 0xA, // GE
            Condition::LessThan => 0xB,           // LT
            Condition::GreaterThan => 0xC,        // GT
            Condition::LessThanOrEqual => 0xD,    // LE
        }
    }
}
